### ISSUE TITLE
I could not Build 

### ISSUE THREAD

**Issue by samnet** [toxeus/go-secp256k1#2]
Hello,
everything works fine for me until the very last command of the build: 

```
dyn905-164:go-secp256k1 samzan$ go install .
# github.com/samzan/go-secp256k1
clang: error: no such file or directory: '../../../github.com/toxeus/go-secp256k1/c-secp256k1/.libs/libsecp256k1.a'

```

I looked around and understand the pb might not be specific to this project, yet I thought perhaps someone ran into the same difficulty and found a solution to it? 

Cheers
(I m a 1st yr CS student)

**Comment by toxeus** [comment]
Looking at your output I can see that the project is not in the correct path 
`# github.com/samzan/go-secp256k1`.
Go is very picky about paths and therefore you need to put this project into
`$GOPATH/src/github.com/toxeus/go-secp256k1`.
Basically, that's what
`go get -d github.com/toxeus/go-secp256k1`
will do for you.

**Comment by toxeus** [comment]
Please reopen this issue if there are still problems in building the project.

**Comment by aminNazarii** [comment]
anybody solve this problem. i still get this error however this project right in this path: $GOPATH/src/github.com/toxeus/go-secp256k1

**Comment by toxeus** [comment]
Hi @aminNazarii. I need more details about your problem. If you cannot describe how to reproduce it then I cannot fix it.
